ALTER TABLE "TaskLine" ADD COLUMN "pauseActive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TaskLine" ADD COLUMN "pauseStart" TEXT;
ALTER TABLE "TaskLine" ADD COLUMN "pauseEnd" TEXT;
ALTER TABLE "TaskLine" ADD COLUMN "pauseYearly" BOOLEAN NOT NULL DEFAULT true;
