// GENDAN SLETTEDE ORDRER fra en Neon-tidsrejse-gren (point-in-time restore).
//
// Baggrund: main-kodens regenerateFutureOrders/kunde-redigering kunne slette
// "næste uge og frem" uden at genskabe (rettet i #25) — genereringen genskaber
// kun abonnements-RYTMEN, aldrig manuelle/online-ordrer, statusser, kommentarer,
// låse eller fakturerings-felter. De skal hentes fra et database-snapshot.
//
// BRUG — altid dry-run først (skriver INTET uden --apply):
//   SOURCE_DATABASE_URL='<neon-tidsrejse-gren>' DATABASE_URL='<produktion>' \
//     npx tsx scripts/restore-missing-orders.ts 2026-08-24 [uger=4] [--apply] [--replace-regenerated]
//
//   SOURCE = Neon Console → projektet → Restore/Branches → "Create branch"
//   fra et tidspunkt FØR sletningen (fx sidste onsdag kl. 12) → kopiér grenens
//   connection string. Grene er gratis/øjeblikkelige — prøv flere tidspunkter,
//   dry-run-rapporten viser præcis hvad hvert snapshot indeholder.
//
// Klassifikation pr. ordre i snapshottet (plannedAt i ugevinduet):
//   FINDES     id eksisterer stadig i produktionen → røres ikke.
//   GENDAN     mangler helt → genindsættes med ORIGINALT id, opgavelinjer,
//              status, kommentarer, låse og fakturerings-felter intakte.
//              Evt. tombstone for (abonnement, rytmeuge) fjernes, så natte-
//              genereringen ikke er blokeret.
//   ERSTATTET  en NYGENERERET ordre (samme abonnement+rytmeuge, nyt id,
//              frisk createdAt) står i stedet → springes over med diff-
//              rapport; med --replace-regenerated byttes den ud med originalen
//              (originalen bærer status/kommentar/lås — den er den rigtige).
//   BLOKERET   ordrens kunde findes ikke længere i produktionen → rapporteres
//              (kunden skal genskabes først).
//
// Efter --apply: kør planlægningen igen (knappen "Genplanlæg uge" eller vent
// på natte-cronen) så de gendannede ordrer ruteplanlægges — og verificér med
// /api/calendar-consistency.
import { PrismaClient } from "@prisma/client";

const WEEK_MS = 7 * 864e5;
const mondayOf = (iso: string) => {
  const d = new Date(`${iso}T00:00:00Z`);
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()) - ((d.getUTCDay() + 6) % 7) * 864e5);
};
const iso = (d: Date) => d.toISOString().slice(0, 10);
const kr = (n: number) => `${n.toLocaleString("da-DK")} kr.`;

async function main() {
  const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  const apply = process.argv.includes("--apply");
  const replaceRegenerated = process.argv.includes("--replace-regenerated");
  const fromArg = args[0];
  if (!fromArg || !/^\d{4}-\d{2}-\d{2}$/.test(fromArg)) {
    console.error("Brug: restore-missing-orders.ts <uge-mandag YYYY-MM-DD> [uger=4] [--apply] [--replace-regenerated]");
    process.exit(2);
  }
  const sourceUrl = process.env.SOURCE_DATABASE_URL;
  if (!sourceUrl) { console.error("SOURCE_DATABASE_URL mangler (Neon-tidsrejse-grenens connection string)."); process.exit(2); }
  const from = mondayOf(fromArg);
  const weeks = Number(args[1]) || 4;
  const to = new Date(from.getTime() + weeks * WEEK_MS);

  const src = new PrismaClient({ datasourceUrl: sourceUrl });
  const tgt = new PrismaClient(); // DATABASE_URL = produktionen

  console.log(`Snapshot vs. produktion — uger ${iso(from)} … ${iso(new Date(to.getTime() - WEEK_MS))} (${weeks} uger)${apply ? "  [APPLY — skriver!]" : "  [dry-run]"}`);

  const srcOrders = await src.order.findMany({
    where: { plannedAt: { gte: from, lt: to } },
    include: { tasks: true, contact: { select: { name: true } } },
    orderBy: { plannedAt: "asc" },
  });
  const srcIds = srcOrders.map((o) => o.id);
  const present = new Set((await tgt.order.findMany({ where: { id: { in: srcIds } }, select: { id: true } })).map((o) => o.id));
  const contactIds = [...new Set(srcOrders.map((o) => o.contactId))];
  const tgtContacts = new Set((await tgt.contact.findMany({ where: { id: { in: contactIds } }, select: { id: true } })).map((c) => c.id));
  // Nygenererede erstatninger: samme (abonnement, rytmeuge), andet id.
  const subWeekKeys = srcOrders.filter((o) => o.subscriptionId != null && o.sourceWeek).map((o) => ({ subscriptionId: o.subscriptionId!, sourceWeek: o.sourceWeek! }));
  const replacements = subWeekKeys.length
    ? await tgt.order.findMany({ where: { OR: subWeekKeys }, include: { tasks: true } })
    : [];
  const replByKey = new Map(replacements.map((o) => [`${o.subscriptionId}|${o.sourceWeek!.toISOString()}`, o]));

  let restored = 0, replaced = 0, conflicts = 0, blocked = 0, existing = 0, tombstonesCleared = 0;
  const sum = (ts: { price: number }[]) => ts.reduce((a, t) => a + t.price, 0);

  for (const o of srcOrders) {
    const label = `#${o.id} ${iso(o.plannedAt)} ${o.contact.name} (${o.sourceType}, ${o.status}, ${kr(sum(o.tasks))})`;
    if (present.has(o.id)) { existing++; continue; }
    if (!tgtContacts.has(o.contactId)) { blocked++; console.log(`  BLOKERET  ${label} — kunden (id ${o.contactId}) findes ikke længere; genskab kunden først`); continue; }

    const key = o.subscriptionId != null && o.sourceWeek ? `${o.subscriptionId}|${o.sourceWeek.toISOString()}` : null;
    const repl = key ? replByKey.get(key) : undefined;
    if (repl && repl.id !== o.id && !replaceRegenerated) {
      conflicts++;
      const diffs: string[] = [];
      if (repl.status !== o.status) diffs.push(`status '${repl.status}'≠'${o.status}'`);
      if (sum(repl.tasks) !== sum(o.tasks)) diffs.push(`pris ${kr(sum(repl.tasks))}≠${kr(sum(o.tasks))}`);
      if (repl.lockedFully !== o.lockedFully) diffs.push("lås afviger");
      if ((repl.comment ?? "") !== (o.comment ?? "")) diffs.push("kommentar afviger");
      if (repl.employeeId !== o.employeeId) diffs.push(`medarbejder ${repl.employeeId}≠${o.employeeId}`);
      console.log(`  ERSTATTET ${label} — nygenereret #${repl.id} står i stedet${diffs.length ? ` (${diffs.join(", ")})` : " (identisk indhold)"} — brug --replace-regenerated for at gendanne originalen`);
      continue;
    }

    console.log(`  ${repl && repl.id !== o.id ? "BYT      " : "GENDAN   "} ${label}${o.comment ? " · kommentar bevaret" : ""}${o.lockedFully ? " · låst" : ""}`);
    if (apply) {
      const { tasks, contact: _c, ...orderRow } = o;
      await tgt.$transaction(async (tx) => {
        if (repl && repl.id !== o.id) {
          await tx.taskLine.deleteMany({ where: { orderId: repl.id } });
          await tx.order.delete({ where: { id: repl.id } });
        }
        await tx.order.create({ data: { ...orderRow, tasks: { create: tasks.map(({ orderId: _o, ...t }) => t) } } });
        if (o.subscriptionId != null && o.sourceWeek) {
          const cleared = await tx.subscriptionWeekSkip.deleteMany({ where: { subscriptionId: o.subscriptionId, week: o.sourceWeek } });
          tombstonesCleared += cleared.count;
        }
      });
      if (repl && repl.id !== o.id) replaced++; else restored++;
    } else if (repl && repl.id !== o.id) replaced++; else restored++;
  }

  if (apply && (restored || replaced)) {
    // Autoincrement-sekvenser skal forbi de genindsatte originale id'er.
    await tgt.$executeRawUnsafe(`SELECT setval(pg_get_serial_sequence('"Order"','id'), (SELECT COALESCE(MAX(id),1) FROM "Order"))`);
    await tgt.$executeRawUnsafe(`SELECT setval(pg_get_serial_sequence('"TaskLine"','id'), (SELECT COALESCE(MAX(id),1) FROM "TaskLine"))`);
  }

  console.log(`\n${apply ? "GENDANNET" : "Dry-run"}: ${restored} gendannet, ${replaced} byttet med original, ${conflicts} erstattet af nygenereret (sprunget over), ${blocked} blokeret, ${existing} fandtes i forvejen${apply ? `, ${tombstonesCleared} tombstones ryddet` : ""}.`);
  if (!apply && (restored || replaced)) console.log("Kør igen med --apply for at skrive. Bagefter: 'Genplanlæg uge' + /api/calendar-consistency.");
  await src.$disconnect(); await tgt.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
